### ISSUE TITLE
marketplace version differs from github releases

### ISSUE THREAD

**Issue by tweigel-dev** [grafana/grafana-json-datasource#344] opened 2023-04-13 17:19 UTC
Hay,
Many thanks for providing such a great plugin!
We noticed that the marketplace version differs from the github release (1.3.3 and 1.3.5).
Also we noticed that there where some bugs regarding queries in the grafana variables since 1.3.5.
**Error updating options: Eval [?(expr)] prevented in JSONPath expression**

Many thanks in advance!

**Comment by DucoApp** [comment] 2023-04-14 06:28
I'm having the same issue...

**Comment by FVE-DUCO** [comment] 2023-04-14 06:30
I'm having the same issues...

**Comment by ghostrider-05** [comment] 2023-04-20 21:24
Getting the same error on version 1.3.4. Queries that do not use expressions are working fine

**Comment by disambiguationuk** [comment] 2023-04-21 08:02
Just noting this is the same as https://github.com/grafana/grafana-json-datasource/issues/343

**Comment by zoltanbedi** [comment] 2023-11-10 13:20
Closing as a duplicate of https://github.com/grafana/grafana-json-datasource/issues/343

**Closed by zoltanbedi** 2023-11-10 13:20 UTC
